language: ruby
rvm:
 - 2.3.3

install: gem install jekyll html-proofer
script: jekyll build && htmlproofer ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

exclude: [vendor]

sudo: false
