language: ruby
rvm:
 - 2.3.4

install:
 - gem install jekyll html-proofer
 - bundle install

script: bundle exec jekyll build && htmlproofer --allow_hash_href --url-ignore "/.onion/" ./_site

branches:
  only:
  - master

cache:
  bundler: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

exclude: [vendor]

sudo: false
